// <auto-generated />
using System;
using HouseHold.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HouseHold.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    [Migration("20260420084752_HouseHold1")]
    partial class HouseHold1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HouseHold.Models.Cart", b =>
                {
                    b.Property<int>("cart_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("cart_id"));

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("cart_id");

                    b.HasIndex("user_id")
                        .IsUnique();

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("HouseHold.Models.CartItem", b =>
                {
                    b.Property<int>("cart_item_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("cart_item_id"));

                    b.Property<int>("cart_id")
                        .HasColumnType("int");

                    b.Property<int>("product_id")
                        .HasColumnType("int");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.HasKey("cart_item_id");

                    b.HasIndex("cart_id");

                    b.HasIndex("product_id");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("HouseHold.Models.Category", b =>
                {
                    b.Property<int>("category_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("category_id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("parent_category_id")
                        .HasColumnType("int");

                    b.HasKey("category_id");

                    b.HasIndex("parent_category_id");

                    b.ToTable("categories");
                });

            modelBuilder.Entity("HouseHold.Models.Comment", b =>
                {
                    b.Property<int>("comment_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("comment_id"));

                    b.Property<string>("comment_text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("moderation_status")
                        .HasColumnType("bit");

                    b.Property<int>("product_id")
                        .HasColumnType("int");

                    b.Property<int>("rating")
                        .HasColumnType("int");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("comment_id");

                    b.HasIndex("product_id");

                    b.HasIndex("user_id");

                    b.ToTable("comments");
                });

            modelBuilder.Entity("HouseHold.Models.Country", b =>
                {
                    b.Property<int>("country_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("country_id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("country_id");

                    b.ToTable("countries");
                });

            modelBuilder.Entity("HouseHold.Models.DeliveryMethod", b =>
                {
                    b.Property<int>("delivery_method_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("delivery_method_id"));

                    b.Property<double>("cost")
                        .HasColumnType("float");

                    b.Property<int>("delivery_days")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("delivery_method_id");

                    b.ToTable("deliveryMethods");
                });

            modelBuilder.Entity("HouseHold.Models.Favorite", b =>
                {
                    b.Property<int>("favorite_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("favorite_id"));

                    b.Property<DateTime>("added_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("product_id")
                        .HasColumnType("int");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("favorite_id");

                    b.HasIndex("product_id");

                    b.HasIndex("user_id", "product_id")
                        .IsUnique();

                    b.ToTable("favorites");
                });

            modelBuilder.Entity("HouseHold.Models.Manufacturer", b =>
                {
                    b.Property<int>("manufacturer_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("manufacturer_id"));

                    b.Property<int>("country_id")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("support_email")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("support_phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("manufacturer_id");

                    b.HasIndex("country_id");

                    b.ToTable("manufacturers");
                });

            modelBuilder.Entity("HouseHold.Models.OrderItem", b =>
                {
                    b.Property<int>("orderItem_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("orderItem_id"));

                    b.Property<int>("order_id")
                        .HasColumnType("int");

                    b.Property<double>("price_at_order")
                        .HasColumnType("float");

                    b.Property<int>("product_id")
                        .HasColumnType("int");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.HasKey("orderItem_id");

                    b.HasIndex("order_id");

                    b.HasIndex("product_id");

                    b.ToTable("orderItems");
                });

            modelBuilder.Entity("HouseHold.Models.OrderStatus", b =>
                {
                    b.Property<int>("status_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("status_id"));

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("status_id");

                    b.ToTable("orderStatuses");
                });

            modelBuilder.Entity("HouseHold.Models.Orders", b =>
                {
                    b.Property<int>("order_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("order_id"));

                    b.Property<DateTime>("completion_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("delivery_address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("delivery_method_id")
                        .HasColumnType("int");

                    b.Property<double>("discount_at_order")
                        .HasColumnType("float");

                    b.Property<string>("order_comment")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("order_number")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("payment_method_id")
                        .HasColumnType("int");

                    b.Property<int>("status_id")
                        .HasColumnType("int");

                    b.Property<int>("total_amount")
                        .HasColumnType("int");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("order_id");

                    b.HasIndex("delivery_method_id");

                    b.HasIndex("payment_method_id");

                    b.HasIndex("status_id");

                    b.HasIndex("user_id");

                    b.ToTable("orders");
                });

            modelBuilder.Entity("HouseHold.Models.ParentCategory", b =>
                {
                    b.Property<int>("parent_category_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("parent_category_id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("parent_category_id");

                    b.ToTable("parentCategories");
                });

            modelBuilder.Entity("HouseHold.Models.PaymentMethod", b =>
                {
                    b.Property<int>("payment_method_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("payment_method_id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("payment_method_id");

                    b.ToTable("paymentMethods");
                });

            modelBuilder.Entity("HouseHold.Models.PriceHistory", b =>
                {
                    b.Property<int>("history_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("history_id"));

                    b.Property<DateTime>("change_date")
                        .HasColumnType("datetime2");

                    b.Property<double>("new_price")
                        .HasColumnType("float");

                    b.Property<double>("old_price")
                        .HasColumnType("float");

                    b.Property<int>("product_id")
                        .HasColumnType("int");

                    b.HasKey("history_id");

                    b.HasIndex("product_id");

                    b.ToTable("priceHistories");
                });

            modelBuilder.Entity("HouseHold.Models.Product", b =>
                {
                    b.Property<int>("product_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("product_id"));

                    b.Property<int>("amount")
                        .HasColumnType("int");

                    b.Property<string>("article")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("category_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<double>("discount_percent")
                        .HasColumnType("float");

                    b.Property<bool>("is_visible")
                        .HasColumnType("bit");

                    b.Property<int>("manufacturer_id")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("supplier_id")
                        .HasColumnType("int");

                    b.Property<double>("weight_kg")
                        .HasColumnType("float");

                    b.HasKey("product_id");

                    b.HasIndex("category_id");

                    b.HasIndex("manufacturer_id");

                    b.HasIndex("supplier_id");

                    b.ToTable("products");
                });

            modelBuilder.Entity("HouseHold.Models.ProductImage", b =>
                {
                    b.Property<int>("image_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("image_id"));

                    b.Property<string>("image_url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("is_primary")
                        .HasColumnType("bit");

                    b.Property<int>("product_id")
                        .HasColumnType("int");

                    b.HasKey("image_id");

                    b.HasIndex("product_id");

                    b.ToTable("productImages");
                });

            modelBuilder.Entity("HouseHold.Models.ProductTag", b =>
                {
                    b.Property<int>("productTag_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("productTag_id"));

                    b.Property<int>("product_id")
                        .HasColumnType("int");

                    b.Property<int>("tag_id")
                        .HasColumnType("int");

                    b.HasKey("productTag_id");

                    b.HasIndex("product_id");

                    b.HasIndex("tag_id");

                    b.ToTable("productTags");
                });

            modelBuilder.Entity("HouseHold.Models.Statuses", b =>
                {
                    b.Property<int>("status_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("status_id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("status_id");

                    b.ToTable("statuses");
                });

            modelBuilder.Entity("HouseHold.Models.Supplier", b =>
                {
                    b.Property<int>("supplier_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("supplier_id"));

                    b.Property<string>("contact_person")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("legal_address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("supplier_id");

                    b.ToTable("suppliers");
                });

            modelBuilder.Entity("HouseHold.Models.SupplyDelivery", b =>
                {
                    b.Property<int>("supply_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("supply_id"));

                    b.Property<DateTime>("delivery_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("invoice_number")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("status_id")
                        .HasColumnType("int");

                    b.Property<int>("supplier_id")
                        .HasColumnType("int");

                    b.Property<int>("total_amount")
                        .HasColumnType("int");

                    b.HasKey("supply_id");

                    b.HasIndex("status_id");

                    b.HasIndex("supplier_id");

                    b.ToTable("supplyDeliveries");
                });

            modelBuilder.Entity("HouseHold.Models.SupplyItem", b =>
                {
                    b.Property<int>("supplyItem_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("supplyItem_id"));

                    b.Property<int>("product_id")
                        .HasColumnType("int");

                    b.Property<double>("purchase_price")
                        .HasColumnType("float");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.Property<int>("supplier_id")
                        .HasColumnType("int");

                    b.HasKey("supplyItem_id");

                    b.HasIndex("product_id");

                    b.HasIndex("supplier_id");

                    b.ToTable("supplyItems");
                });

            modelBuilder.Entity("HouseHold.Models.Tag", b =>
                {
                    b.Property<int>("tag_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("tag_id"));

                    b.Property<string>("tag_name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("tag_id");

                    b.ToTable("tags");
                });

            modelBuilder.Entity("HouseHold.Models.UserRole", b =>
                {
                    b.Property<int>("role_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("role_id"));

                    b.Property<string>("role_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("role_id");

                    b.ToTable("userRoles");
                });

            modelBuilder.Entity("HouseHold.Models.Users", b =>
                {
                    b.Property<int>("user_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("user_id"));

                    b.Property<double>("discount")
                        .HasColumnType("float");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("first_name")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("last_login_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("last_name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("registration_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("role_id")
                        .HasColumnType("int");

                    b.HasKey("user_id");

                    b.HasIndex("role_id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("HouseHold.Models.Cart", b =>
                {
                    b.HasOne("HouseHold.Models.Users", "User")
                        .WithOne("Cart")
                        .HasForeignKey("HouseHold.Models.Cart", "user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HouseHold.Models.CartItem", b =>
                {
                    b.HasOne("HouseHold.Models.Cart", "Cart")
                        .WithMany("Items")
                        .HasForeignKey("cart_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HouseHold.Models.Product", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("product_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("HouseHold.Models.Category", b =>
                {
                    b.HasOne("HouseHold.Models.ParentCategory", "parentCategory")
                        .WithMany("categories")
                        .HasForeignKey("parent_category_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("parentCategory");
                });

            modelBuilder.Entity("HouseHold.Models.Comment", b =>
                {
                    b.HasOne("HouseHold.Models.Product", "product")
                        .WithMany("comments")
                        .HasForeignKey("product_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HouseHold.Models.Users", "users")
                        .WithMany("comments")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("product");

                    b.Navigation("users");
                });

            modelBuilder.Entity("HouseHold.Models.Favorite", b =>
                {
                    b.HasOne("HouseHold.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("product_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HouseHold.Models.Users", "User")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HouseHold.Models.Manufacturer", b =>
                {
                    b.HasOne("HouseHold.Models.Country", "country")
                        .WithMany("manufacturers")
                        .HasForeignKey("country_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("country");
                });

            modelBuilder.Entity("HouseHold.Models.OrderItem", b =>
                {
                    b.HasOne("HouseHold.Models.Orders", "Orders")
                        .WithMany("orderItems")
                        .HasForeignKey("order_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HouseHold.Models.Product", "Product")
                        .WithMany("orderItems")
                        .HasForeignKey("product_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Orders");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("HouseHold.Models.Orders", b =>
                {
                    b.HasOne("HouseHold.Models.DeliveryMethod", "deliveryMethod")
                        .WithMany("orders")
                        .HasForeignKey("delivery_method_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HouseHold.Models.PaymentMethod", "paymentMethod")
                        .WithMany("orders")
                        .HasForeignKey("payment_method_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HouseHold.Models.OrderStatus", "status")
                        .WithMany("orders")
                        .HasForeignKey("status_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HouseHold.Models.Users", "user")
                        .WithMany("orders")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("deliveryMethod");

                    b.Navigation("paymentMethod");

                    b.Navigation("status");

                    b.Navigation("user");
                });

            modelBuilder.Entity("HouseHold.Models.PriceHistory", b =>
                {
                    b.HasOne("HouseHold.Models.Product", "Product")
                        .WithMany("priceHistories")
                        .HasForeignKey("product_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("HouseHold.Models.Product", b =>
                {
                    b.HasOne("HouseHold.Models.Category", "category")
                        .WithMany("products")
                        .HasForeignKey("category_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HouseHold.Models.Manufacturer", "manufacturer")
                        .WithMany("products")
                        .HasForeignKey("manufacturer_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HouseHold.Models.Supplier", "supplier")
                        .WithMany("products")
                        .HasForeignKey("supplier_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("category");

                    b.Navigation("manufacturer");

                    b.Navigation("supplier");
                });

            modelBuilder.Entity("HouseHold.Models.ProductImage", b =>
                {
                    b.HasOne("HouseHold.Models.Product", "Product")
                        .WithMany("productImages")
                        .HasForeignKey("product_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("HouseHold.Models.ProductTag", b =>
                {
                    b.HasOne("HouseHold.Models.Product", "Product")
                        .WithMany("productTags")
                        .HasForeignKey("product_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HouseHold.Models.Tag", "Tag")
                        .WithMany("productTags")
                        .HasForeignKey("tag_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("HouseHold.Models.SupplyDelivery", b =>
                {
                    b.HasOne("HouseHold.Models.Statuses", "statuses")
                        .WithMany("supplyDeliveries")
                        .HasForeignKey("status_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HouseHold.Models.Supplier", "supplier")
                        .WithMany("supplyDeliveries")
                        .HasForeignKey("supplier_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("statuses");

                    b.Navigation("supplier");
                });

            modelBuilder.Entity("HouseHold.Models.SupplyItem", b =>
                {
                    b.HasOne("HouseHold.Models.Product", "product")
                        .WithMany("supplyItems")
                        .HasForeignKey("product_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HouseHold.Models.Supplier", "supplier")
                        .WithMany("supplyItems")
                        .HasForeignKey("supplier_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("product");

                    b.Navigation("supplier");
                });

            modelBuilder.Entity("HouseHold.Models.Users", b =>
                {
                    b.HasOne("HouseHold.Models.UserRole", "UserRole")
                        .WithMany("Users")
                        .HasForeignKey("role_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserRole");
                });

            modelBuilder.Entity("HouseHold.Models.Cart", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("HouseHold.Models.Category", b =>
                {
                    b.Navigation("products");
                });

            modelBuilder.Entity("HouseHold.Models.Country", b =>
                {
                    b.Navigation("manufacturers");
                });

            modelBuilder.Entity("HouseHold.Models.DeliveryMethod", b =>
                {
                    b.Navigation("orders");
                });

            modelBuilder.Entity("HouseHold.Models.Manufacturer", b =>
                {
                    b.Navigation("products");
                });

            modelBuilder.Entity("HouseHold.Models.OrderStatus", b =>
                {
                    b.Navigation("orders");
                });

            modelBuilder.Entity("HouseHold.Models.Orders", b =>
                {
                    b.Navigation("orderItems");
                });

            modelBuilder.Entity("HouseHold.Models.ParentCategory", b =>
                {
                    b.Navigation("categories");
                });

            modelBuilder.Entity("HouseHold.Models.PaymentMethod", b =>
                {
                    b.Navigation("orders");
                });

            modelBuilder.Entity("HouseHold.Models.Product", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("comments");

                    b.Navigation("orderItems");

                    b.Navigation("priceHistories");

                    b.Navigation("productImages");

                    b.Navigation("productTags");

                    b.Navigation("supplyItems");
                });

            modelBuilder.Entity("HouseHold.Models.Statuses", b =>
                {
                    b.Navigation("supplyDeliveries");
                });

            modelBuilder.Entity("HouseHold.Models.Supplier", b =>
                {
                    b.Navigation("products");

                    b.Navigation("supplyDeliveries");

                    b.Navigation("supplyItems");
                });

            modelBuilder.Entity("HouseHold.Models.Tag", b =>
                {
                    b.Navigation("productTags");
                });

            modelBuilder.Entity("HouseHold.Models.UserRole", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("HouseHold.Models.Users", b =>
                {
                    b.Navigation("Cart")
                        .IsRequired();

                    b.Navigation("comments");

                    b.Navigation("orders");
                });
#pragma warning restore 612, 618
        }
    }
}
